# Jekyll config precedence:
# 1. Gulpfile task
# 2. config.build.yml
# 3. config.yml

name: koda.agency
description:
url: http://www.koda.agency

markdown: redcarpet
highlighter: pygments

baseurl: ''

# Gulp handles images and assets
exclude: ['**.sass','assets/*', 'img', 'sass', 'css', 'js', 'fonts', '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

keep_files: ['assets']
